version: "3.8"
volumes:
  db_data:
services:
  mysql_db:
   image: mysql:8.0
   environment:
     - MYSQL_DATABASE=employees
     - MYSQL_USER=root
     - MYSQL_ROOT_PASSWORD=root
   networks:
     - db
     - application
   volumes:
     - /Users/macuser/Downloads/demo/insert.sql:/usr/data/insert.sql
  app:
   image: employeeApi:latest
   command: ["java","-jar","/app.jar"]
   ports:
     - '8081:8080'
   working_dir: /usr/src/app
   environment:
     - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/employees?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
   depends_on:
     - database
   networks:
   - application
   - db
  networks:
   db:
   app: